/**
 * Created by Raphael Karanja on 2019-02-25.
 */

//LOGIN
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

//EVENTS
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';

